name: Release Packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - mips_24kc
          - mipsel_24kc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: mihomo
          PACKAGES: luci-app-mihomo
          NO_REFRESH_CHECK: true

      - name: Compress
        run: |
          tar -c -z -f mihomo_${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/mihomo .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mihomo_${{ matrix.arch }}.tar.gz
